apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gjermund-spk

resources:
  - service.yaml
  - http-route.yaml
  - deployment.yaml

configMapGenerator:
  - name: whatami-config
    namespace: gjermund-spk
    literals:
      - whatami_PORT_NUMBER=8080
